[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.top =        [{ monitor."built-in" = 20 }, { monitor.main = 55 }, 0]
outer.right =      [{ monitor."built-in" = 10 }, { monitor.main = 10 }, 0]
outer.bottom =     [{ monitor."built-in" = 10 }, { monitor.main = 10 }, 0]
outer.left =       [{ monitor."built-in" = 10 }, { monitor.main = 10 }, 0]
