[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.top =        [{ monitor."built-in" = 12 }, { monitor.main = 45 }, 0]
outer.right =      [{ monitor."built-in" = 5 }, { monitor.main = 5 }, 0]
outer.bottom =     [{ monitor."built-in" = 5 }, { monitor.main = 5 }, 0]
outer.left =       [{ monitor."built-in" = 5 }, { monitor.main = 5 }, 0]
